---
- name: Ensure HAProxy is installed.
  package: name=haproxy state=present
  tags: install

- name: Ensure HAProxy is enabled (so it starts on Debian)
  lineinfile:
    dest: /etc/default/haproxy
    regexp: "^ENABLED.+$"
    line: "ENABLED=1"
    state: present
  when: ansible_os_family == 'Debian'
  tags: configure

- name: Get HAProxy version.
  command: haproxy -v
  register: haproxy_version_result
  changed_when: false
  check_mode: false
  tags: configure

- name: Set HAProxy version.
  set_fact:
    haproxy_version: "{{ '1.5' if '1.5.' in haproxy_version_result.stdout else '1.4' }}"
  tags: configure

- name: Print certificate details
  debug:
    msg:
    - Host {{ item }} uses {{ item.https_certificate }} and {{ item.https_private_key }} that forms {{ item.https_private_key_content }}
  with_items:
     - "{{ certs }}"
  tags: install_pem_files

- name: Deploy public certificate and deploy private key
  copy:
    content: |
      {{ item.https_private_key_content }}
      {{ item.https_certificate_content }}
    dest: "{{ crt_path }}/{{ item.https_pem }}"
    mode: 0644
  with_items:
    - "{{ certs }}"
  tags: install_pem_files

- name: Copy HAProxy configuration in place.
  template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
    mode: 0644
    validate: haproxy -f %s -c -q
  notify: restart haproxy
  tags: configure

- name: Ensure HAProxy is started and enabled on boot
  service: name=haproxy state=started enabled=yes
  tags: configure

